@isTest
public with sharing class TestProductTriggerHelper {
    // @isTest
    // static void TestSingleRecord(){
    //     Double price = 4.99;
    //     //Map<Id, Product2> p = new Product2(Name='3 Ring Binder', Family='Binders & Folders', Product_Price__c = price);

    //     Map<Id,Product2> p = new Product2(Name='3 Ring Binder', Family='Binders & Folders', Product_Price__c = price);
    //     insert p; 
    //     ProductTriggerHelper.addStandardPrice(p);

    //     PricebookEntry pe = [SELECT Product2Id FROM PricebookEntry];
    //     System.assertEquals(4.99, pe.UnitPrice);
    // }
}
